# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 03:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=140)),
                ('created', models.DateTimeField(default=datetime.datetime(2016, 4, 5, 3, 43, 54, 271484, tzinfo=utc))),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
