# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 03:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 5, 3, 43, 59, 264419, tzinfo=utc)),
        ),
    ]
